settings_file: "settings_sobec.yaml"
left_foot_name: "left_sole_link"
right_foot_name: "right_sole_link"
urdf: "/opt/openrobots/share/example-robot-data/robots/talos_data/robots/talos_reduced.urdf"
srdf: "/opt/openrobots/share/example-robot-data/robots/talos_data/srdf/talos.srdf"
controlled_joints:
  [
    root_joint,
    leg_left_1_joint,
    leg_left_2_joint,
    leg_left_3_joint,
    leg_left_4_joint,
    leg_left_5_joint,
    leg_left_6_joint,
    leg_right_1_joint,
    leg_right_2_joint,
    leg_right_3_joint,
    leg_right_4_joint,
    leg_right_5_joint,
    leg_right_6_joint,
    torso_1_joint,
    torso_2_joint,
    arm_left_1_joint,
    arm_left_2_joint,
    arm_left_3_joint,
    arm_left_4_joint,
    arm_left_5_joint,
    arm_left_6_joint,
    arm_left_7_joint,
    arm_right_1_joint,
    arm_right_2_joint,
    arm_right_3_joint,
    arm_right_4_joint,
  ]
tool_frame_pos: [0, -0.02, -0.0825]