robot:
  toolFramePos: [0, -0.02, -0.0825]
  controlledJoints: [
    root_joint, 
    leg_left_1_joint,
    leg_left_2_joint,
    leg_left_3_joint,
    leg_left_4_joint,
    leg_left_5_joint,
    leg_left_6_joint,
    leg_right_1_joint,
    leg_right_2_joint,
    leg_right_3_joint,
    leg_right_4_joint,
    leg_right_5_joint,
    leg_right_6_joint,
    torso_1_joint,
    torso_2_joint,
    arm_left_1_joint,
    arm_left_2_joint,
    arm_left_3_joint,
    arm_left_4_joint,
    arm_left_5_joint,
    arm_left_6_joint,
    arm_left_7_joint,
    arm_right_1_joint,
    arm_right_2_joint,
    arm_right_3_joint,
    arm_right_4_joint,
  ]

ocp-point:
  horizon_length: 100
  wStateReg: 0.02
  wControlReg: 0.001
  wLimit: 1000
  wPCoM: 500
  wVCoM: 0
  wWrenchCone: 0
  wGripperPos: 7
  wGripperRot: 30
  wGripperVel: 2
  scaleLimits: 1
  statePosWeights:
    base: [500, 500, 500, 1000, 1000, 1000]
    leftLeg: [500, 500, 500, 500, 1000, 1000]
    rightLeg: [500, 500, 500, 500, 1000, 1000]
    torso: [100, 200]
    leftArm: [100, 100, 100, 100, 1, 1, 1]
    rightArm: [500, 500, 500, 500]
  stateVelWeights:
    base: [1, 1, 1, 1, 1, 1]
    leftLeg: [1, 1, 1, 1, 1, 1]
    rightLeg: [1, 1, 1, 1, 1, 1]
    torso: [10, 10]
    leftArm: [10, 10, 10, 10, 10, 10, 10]
    rightArm: [10, 10, 10, 10]
  controlWeights:
    leftLeg: [1, 1, 1, 1, 1, 1]
    rightLeg: [1, 1, 1, 1, 1, 1]
    torso: [1, 1]
    leftArm: [1, 1, 1, 1, 1, 1, 1]
    rightArm: [1, 1, 1, 1]

mpc-point:
  T_initialization: 100
  T_stabilization: 200
  T_drilling: 100
  targetPos: [0.6,0.4,1.1]
  holes_offsets: [
    [0,0,0],
    [-0.078,0,0],
    [-0.078,-0.045,0],
    [0,-0.045,0]
  ]
  backwardOffset: 0.05
  tolerance: 0.005
  maxGoalWeight: 100
  use_mocap: 0
  use_gainScheduling: 1
  gainSchedulig_slope: 0.5


